cargo-features = ["edition"]

[package]
name = "algorithms"
version = "0.1.0"
edition = "2018"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]

[dev-dependencies]
rand = "0.5"
statistical = "0.1.1"
